# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EOS_Client' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'PromiseKit'
  pod 'SwiftyJSON'
  pod 'MBProgressHUD'

  # Pods for EOS_Client

  target 'EOS_ClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EOS_ClientUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
